# Generated by Django 3.2.7 on 2021-09-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imageUrl', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('category', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
