# Generated by Django 3.2.7 on 2021-09-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20210913_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='sizes',
            field=models.CharField(default='[26,30,40]', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='types',
            field=models.CharField(default='[0,1]', max_length=20),
        ),
    ]
