# Generated by Django 3.2.7 on 2021-09-13 10:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_auto_20210913_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=3),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2),
        ),
    ]
